Import('env')

env.Program('chatserver',
            ['main.cpp',
             'apihandler.cpp'],
            LIBPATH=['#/src/']+env.get('LIBPATH',[]),
            LIBS = ['qhttpengine']+env.get('LIBS',[]))
